### ISSUE TITLE
Incorrect book abbreviations for Ecclesiastes

### ISSUE THREAD

**Issue by simonminer** [reubenlillie/daily-office#3]
Hi @reubenlillie,

It appears that the book abbreviations for Ecclesiastes in readings during Proper 4 and Proper 5 in Year Two are inaccurate.  The book abbreviation used in the JSON is "Sir", but in the BCP 2007, it is "Eccles" (see pages 969 and 971 of BCP 2007).  The chapter and verse references look correct.

Would you please confirm this?  If you'd like, I can submit a pull request with a fix.

Thanks.

- @simonminer

**Comment by reubenlillie** [comment]
@simonminer, a pull request would be helpful. BCP uses "Eccles" for Ecclesiastes and "Ecclus" for Ecclesiasticus (aka Sirach from the Apocrypha). The similarity is among the reasons why I opted for standard abbreviations from the Society of Biblical Literature (i.e. "Sir"). However, I'm not above entering the data incorrectly for certain propers.

**Comment by simonminer** [comment]
Based on BPC 2007, I believe the readings in question are from Ecclesiastes, and not Sirach/Ecclesiasticus.  Pull request coming shortly.
